### ISSUE TITLE
Library spams app startup w/ "=PROGRESS REPORT="s

### ISSUE THREAD

**Issue by coladarci** [Decisiv/json_api_client#1]
When adding this library, my app gets spammed w/ hundreds of progress reports:
```
...
=PROGRESS REPORT==== 29-Nov-2017::16:07:23 ===
         application: package_one
          started_at: 'my-app-name-local@127.0.0.1'

=PROGRESS REPORT==== 29-Nov-2017::16:07:23 ===
         application: package_two
          started_at: 'my-app-name-local@127.0.0.1'

=PROGRESS REPORT==== 29-Nov-2017::16:07:23 ===
         application: package_three
          started_at: 'my-app-name-local@127.0.0.1'
...
```

Any ideas? Library works great so far though...

**Comment by gfmurphy** [comment]
@coladarci These are probably being added by the `sasl` application, which is a dependency of the `fuse` middleware. You can configure `sasl` in your application to ignore progress reports by configuring it to only log errors:

```elixir
config :sasl, errlog_type: :error
```

**Comment by coladarci** [comment]
Thanks! Out of curiosity, why fuse is needed for the client? Seems like a strong ask to add the dependency..

**Comment by gfmurphy** [comment]
🤔 I believe it's only technically required if you're using the circuit breaker middleware, but it's being started as an extra application.

I totally agree we could improve this. I will mention it to the rest of the team on Monday, and we'll see if we can improve it. Thanks!

**Comment by bundacia** [comment]
Yeah, seems like we could make fuse usage configurable.

**Comment by coladarci** [comment]
That'd be awesome - I have a fork w/ it removed completely but would much rather you folks do it the way you actually feel comfortable..
