### ISSUE TITLE
Possible incorrect typespec

### ISSUE THREAD

**Issue by amiel** [Decisiv/json_api_client#13]
I am setting up some `@spec` contracts in my application and found what I think is an incorrect typespec in `JsonApiClient.Document`.

In `JsonApiClient.Document`, the `data` attribute [is listed as `[JsonApiClient.ResourceIdentifier.t()] | JsonApiClient.ResourceIdentifier.t() | nil`](https://github.com/Decisiv/json_api_client/blob/master/lib/json_api_client/document.ex#L143), but I believe it should also include `JsonApiClient.Resource.t()`, like so: `[JsonApiClient.Resource.t()] | [JsonApiClient.ResourceIdentifier.t()] | JsonApiClient.Resource.t() | JsonApiClient.ResourceIdentifier.t() | nil`.

Similarly, I think that `included` should also allow `JsonApiClient.Resource.t()`, [but doesn't](https://github.com/Decisiv/json_api_client/blob/master/lib/json_api_client/document.ex#L146).

I'd be happy to work on a change, but I wanted to verify that I am thinking about this correctly first.

**Comment by amiel** [comment]
I've also found another similar situation.

`JsonApiClient.Request.resource/2` takes a `JsonApiClient.Resource.t()`, but there's no way to make a request with a list or with a `ResourceIdentifier` (or a list of `ResourceIdentifier`s) and follow the spec correctly.

**Comment by tapajos** [comment]
@amiel I'm not working on that project anymore and a little bit busy to make any work on this. I know that this kind of answer is very frustrated....

Without any deep investigation I think that you are thinking correctly.

However, I can review and accept any PR that you want  to put.

**Comment by amiel** [comment]
@tapajos I totally understand being too busy to work on this.

I appreciate your validation that I'm on the right track!

If you would be willing to do just enough to review my PR and release it if you think it's good, that's enough for me. I'll work on a PR soon.
