### ISSUE TITLE
Timeout setting not taking effect

### ISSUE THREAD

**Issue by doughsay** [Decisiv/json_api_client#2]
Using this in my `config/config.exs`:

```elixir
config :json_api_client, timeout: 5000
```

...seems to have no effect.  It still times out after 500ms.

I read the code, and can't seem to find out why this would be.

In my IEx console:

```elixir
> Application.get_env(:json_api_client, :timeout)
5000
```

I'm contacting an external payment gateway through this request, so 500ms is way too low, the requests take on average 1.5 seconds...

**Comment by doughsay** [comment]
Sorry, false alarm.  The issue is that you're reading and storing the application settings at compile time.  Which means changing it in your config.exs takes no effect unless you force-recompile your dependencies.  I'd suggest reading the configuration value at runtime to limit this confusion.

**Comment by gfmurphy** [comment]
As of  `VERSION 2.0.1` we're no longer doing this. Thanks for the report!
