### ISSUE TITLE
can httppoison version be updated?

### ISSUE THREAD

**Issue by melbardis** [Decisiv/json_api_client#7]

**Comment by melbardis** [comment]
hi, the current version of httpoison is around 1.0,
you project calls out 0.13 ...


can this be changed to use the latest poison???

**Comment by tapajos** [comment]
Hi @melbardis,

I don't see any problem updating it if we confirm that it still working as expected. Do you mind submit a PR updating it?

**Comment by tapajos** [comment]
PR created: https://github.com/Decisiv/json_api_client/pull/8

**Comment by tapajos** [comment]
@melbardis released as `3.1.0`

**Comment by melbardis** [comment]
hi, great response time.

i will try working with the code to day, if i have other issues i will be sure to let you know

thanks again...
eric
