### ISSUE TITLE
is it possible to disable automatic inference of request paths?

### ISSUE THREAD

**Issue by mus0u** [Decisiv/json_api_client#9]
i'm trying to interact with an api that requires singular-inflected values for the type field on its resources, but which has plural path names, e.g. a resource of type "user" will be sent to the path `"/users"`.

i tried specifying the path manually with a string as mentioned in the README, but the resource type still gets appended to the end. so if i try, for example:
```elixir
user_resource = %Resource{type: "user", attributes: %{...}}
base_url()
|> Request.new()
|> Request.resource(user_resource)
|> Request.path("/users")
|> JsonApiClient.create()
```

it constructs the path as `"<base_url>/users/user"` instead of `"<base_url>/users"`.

i can see the automatic inference of URL paths from a resource's type field being very handy in most circumstances, but in this case it's preventing me from being able to do what i need. is there a way to disable or circumvent this feature?

**Comment by gfmurphy** [comment]
👋 @mus0u This looks like a bug to me in the `Request.get_url` function. IMO what you're doing should produce the results you expect. i.e. `get_url` should not try to infer the path from the provided resource if an explicit path has been provided.

I might be able to get a PR up tomorrow that will address this. we'll see. We'd happily accept a PR from the community too 👍.

Thanks for the report 😄

**Comment by mus0u** [comment]
since i need this for my day job i'm gonna take a whack at it right now.
